apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  mongodb-uri: mongodb://mongo:27017
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
data:
  jwt-secret: eW91cl9qd3Rfc2VjcmV0